language: r
r:
  - oldrel
  - release
  - devel
sudo: required
cache: packages
apt_packages:
  - oracle-java8-installer
  - oracle-java8-set-default
before_script:
  - R CMD javareconf
r_packages:
  - devtools
